name: fviz-ui

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/fviz-ui.yml
      - packages/fviz-ui/**
      - '!**/*.md'
  pull_request:
    paths:
      - .github/workflows/fviz-ui.yml
      - packages/fviz-ui/**
      - '!**/*.md'
env:
  SKIP_PREFLIGHT_CHECK: true
jobs:

  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.5
      - name: Checkout current git repository
        uses: actions/checkout@v2
      - name: Install yarn dependencies
        run: yarn --cwd packages/fviz-ui/ install --immutable
      - name: Build
        id: yarn_build
        run: yarn --cwd packages/fviz-ui/ build
      - name: Test
        id: yarn_test
        run: yarn --cwd packages/fviz-ui/ test
