on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/fviz-server.yml
      - packages/fviz-server/**
      - '!**/*.md'
  pull_request:
    paths:
      - .github/workflows/fviz-server.yml
      - packages/fviz-server/**
      - '!**/*.md'
name: fviz-server

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path packages/fviz-server/Cargo.toml

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path packages/fviz-server/Cargo.toml

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path packages/fviz-server/Cargo.toml -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path packages/fviz-server/Cargo.toml -- -D warnings
          

      
