name: fviz-simulator
on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/fviz-simulator.yml
    - packages/fviz-simulator/**
  pull_request:
    paths:
    - .github/workflows/fviz-simulator.yml
    - packages/fviz-simulator/**
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Checkout current git repository
      uses: actions/checkout@v2
    - name: Install Go dependencies
      run: make -C packages/fviz-simulator/ install
    - name: Build Go code
      run: make -C packages/fviz-simulator/ build
    - name: Test Go code
      run: make -C packages/fviz-simulator/ test
